version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - 'type: chore'
      - 'area: ci-cd'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - 'type: chore'
      - 'area: ci-cd'
